version: '3'

services:
  bot:
    build: .
    restart: always
    container_name: bot_tests_bot
    command: python3 main.py
    volumes:
      - data:/home/app/bot/src/data
    env_file:
      - ./config/.prod.env
      - ./config/.prod.redis.env
    depends_on:
      - redis
  
  redis:
    image: redis
    restart: always
    container_name: bot_tests_redis
    env_file:
      - ./config/.prod.redis.env
    ports:
      - 6379:6379

volumes:
  data: